//SYSTEM DEFINES
#define EXIT_SUCESS 0
#define EXIT_FAIL 1
#define DEFAULT_BUFFLEN 512

//NETWORK DEFINES
#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 27015

//COMMAND DEFINES
#define COMMAND_MAX_LEN 20
#define PARAM_MAX_LEN 10
